import React from 'react';

export const metadata = {
  title: "Create Next App - About",
  description: "Generated by create next app",
};
const About = () => {
  return (
    <div>
      <h1>About page</h1>
    </div>
  );
};

export default About;