import React from 'react';

export const metadata = {
  title: "Create Next App - product",
  description: "Generated by create next app",
};
const ProductPage = () => { 
  return (
    <div>
      <h1>this is product page</h1>
    </div>
  );
};

export default ProductPage;