import React from 'react';

export const metadata = {
  title: "Create Next App - contact",
  description: "Generated by create next app",
};
const Contact = () => {
  return (
    <div>
      <h1>Contact page</h1>
    </div>
  );
};

export default Contact;